function [Lambda, Ap] = calib_iter_restore_matrix(p_seq)

Lambda = cell(1, 5);
Ap = cell(1, 5);

% SPR
Ap{1} = blkdiag(Ap_m(p_seq(:,1)), ...
                Ap_m(p_seq(:,2)), ...
                Ap_m(p_seq(:,3)), ...
                Ap_m(p_seq(:,4)), ...
                Ap_m(p_seq(:,5)), ...
                Ap_m(p_seq(:,6)));


T1 = zeros(4,4,6);
for i_joint = 1 : 6
    T1(:,:,i_joint) = exp_se3(p_seq(:, i_joint));
end

Lambda{1} = blkdiag(eye(6), ...
                adjoint_m(T1(:,:,1)), ...
                adjoint_m(T1(:,:,1)*T1(:,:,2)), ...
                adjoint_m(T1(:,:,1)*T1(:,:,2)*T1(:,:,3)), ...
                adjoint_m(T1(:,:,1)*T1(:,:,2)*T1(:,:,3)*T1(:,:,4)), ...
                adjoint_m(T1(:,:,1)*T1(:,:,2)*T1(:,:,3)*T1(:,:,4)*T1(:,:,5))  );



% UPS
T2 = zeros(4,4,7);
for i_limb = 2 : 5
    Ap{i_limb} = blkdiag( ...
                Ap_m(p_seq(:, 7*(i_limb-1))), ...
                Ap_m(p_seq(:, 7*(i_limb-1)+1)), ...
                Ap_m(p_seq(:, 7*(i_limb-1)+2)), ...
                Ap_m(p_seq(:, 7*(i_limb-1)+3)), ...
                Ap_m(p_seq(:, 7*(i_limb-1)+4)), ...
                Ap_m(p_seq(:, 7*(i_limb-1)+5)), ...
                Ap_m(p_seq(:, 7*(i_limb-1)+6)) ...
                );

    for i_joint = 1 : 7
        T2(:,:,i_joint) = exp_se3(p_seq(:, (7*(i_limb-1) - 1) + i_joint));
    end
    Lambda{i_limb} = blkdiag( ...
                eye(6), ...
                adjoint_m(T2(:,:,1)), ...
                adjoint_m(T2(:,:,1)*T2(:,:,2)), ...
                adjoint_m(T2(:,:,1)*T2(:,:,2)*T2(:,:,3)), ...
                adjoint_m(T2(:,:,1)*T2(:,:,2)*T2(:,:,3)*T2(:,:,4)), ...
                adjoint_m(T2(:,:,1)*T2(:,:,2)*T2(:,:,3)*T2(:,:,4)*T2(:,:,5)), ...
                adjoint_m(T2(:,:,1)*T2(:,:,2)*T2(:,:,3)*T2(:,:,4)*T2(:,:,5)*T2(:,:,6)) ...
                    );
end



end


function A = Ap_m(screw)
    omega = screw(1:3);
    nu = screw(4:6);
    
    Z = [skew(omega) zeros(3,3); skew(nu) skew(omega)];
    phi = norm(omega);  % 是旋转模长，不包括线速度

    if phi < 1e-5
        A = eye(6) + 0.5 * Z + (1/6) * (Z*Z);
    else
        S = sin(phi);
        C = cos(phi);
        
        c1 = (4 - phi*S - 4*C) / (2*phi^2);
        c2 = (4*phi - 5*S + phi*C) / (2*phi^3);
        c3 = (2 - phi*S - 2*C) / (2*phi^4);
        c4 = (2*phi - 3*S + phi*C) / (2*phi^5);
        
        Z2 = Z*Z;
        Z3 = Z2*Z;
        Z4 = Z3*Z;
        
        A = eye(6) + c1*Z + c2*Z2 + c3*Z3 + c4*Z4;
    end
end